#!/bin/bash

[ -v _RESPONSE_MODULE_ ] &&
    return 0 || _RESPONSE_MODULE_=

declare -A _RESPONSE_STATUS
_RESPONSE_STATUS_CODE=200
_RESPONSE_STATUS_MSG=

declare -A _RESPONSE_HEADERS

_RESPONSE_HEADERS['Content-type']='text/html'

declare -A _RESPONSE_COOKIES

response::set_status() {
    [ $# -lt 1 ] && return 1
    _RESPONSE_STATUS_CODE=$1
    _RESPONSE_STATUS_MSG=$2
    return 0
}

# key=$1 value=$2 Path=$3 domain=$4
response::set_cookie() {
    [ $# -lt 2 ] && return 1
    local tmp="${2};path=${3:-/}"
    [ -v $4 ] && tmp="${tmp};domain=$4"
    _RESPONSE_COOKIES[$1]=$tmp
}

response::headers() {
    printf "Status: $_RESPONSE_STATUS_CODE"
    [ "$_RESPONSE_STATUS_MSG" ] &&
        printf " ${_RESPONSE_STATUS_MSG}"
    printf "\n"

    for index in ${!_RESPONSE_HEADERS[@]}; do
        echo "${index}: ${_RESPONSE_HEADERS[$index]}"
    done

    for index in ${!_RESPONSE_COOKIES[@]}; do
        echo "Set-Cookie: ${index}=${_RESPONSE_COOKIES[$index]}"
    done

    printf "\n"
    return 0
}
