#!/bin/bash

. $__DIR__/dao/user

home() {
    echo "home"
} 2>&1

test() {
    DB::setTable users
    DB::filter "id='${INPUT[aaa]}'"
    DB::query
} 2>&1

user() {
    echo id: $id
    echo page: $page
}
