#!/bin/bash

. $__DIR__/lib/petunia/database/database

migration.up() {
    DB::setTable users
    DB::setPrimaryKey 'id'

    DB::setColumn 'name' 'varchar(32)'
    DB::setColumn 'password' 'varchar(32)' # using md5sum

    DB::createTable
}

migration.down() {
    DB::setTable users
    DB::dropTable
}
